init:
	python -m pip install -r requirements.txt

gui:
	python .\quikgui.py

barrel:
	python .\quikplan_barrel_racing.py

slalom:
	python .\quikplan_slalom.py

bounce:
	python .\quikplan_bounce.py
